homepage:
  path: /
  defaults: { _controller: BlogBundle:Blog:teaser }

blog_teaser:
  path: /blog
  defaults: { _controller: BlogBundle:Blog:teaser }

blog_view:
  path: /blog/{id}
  defaults: { _controller: BlogBundle:Blog:blogView }
  requirements:
    id: \d+

blog_about:
  path: /about
  defaults: { _controller: BlogBundle:Page:aboutUs }

admin_page:
  path: /admin
  defaults: { _controller: BlogBundle:Admin:index }